
controller_list:
  - name: fake_arm_group_controller
    type: interpolate
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
      
initial:
  - group: arm_group
    pose: init_pose
  
