#firefighter:
# Simulation settings for using moveit_sim_controllers
#moveit_sim_hw_interface:
#    joint_model_group: arm_group
#    joint_model_group_pose: init_pose
# Settings for ros_control_boilerplate control loop
#generic_hw_control_loop:
#    loop_hz: 300
#    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
#hardware_interface:
#    joints:
#      - joint2_to_joint1
#      - joint3_to_joint2
#      - joint4_to_joint3
#      - joint5_to_joint4
#      - joint6_to_joint5
#      - joint6output_to_joint6
#    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
arm_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint2_to_joint1
        - joint3_to_joint2
        - joint4_to_joint3
        - joint5_to_joint4
        - joint6_to_joint5
        - joint6output_to_joint6
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
        joint2_to_joint1: {trajectory: 1, goal: 0.01}
        joint3_to_joint2: {trajectory: 1, goal: 0.01}
        joint4_to_joint3: {trajectory: 1, goal: 0.01}
        joint5_to_joint4: {trajectory: 1, goal: 0.01}
        joint6_to_joint5: {trajectory: 1, goal: 0.01}
        joint6output_to_joint6: {trajectory: 1, goal: 0.01}
      stop_trajectory_duration: 0.2
      state_publish_rate:  25
      action_monitor_rate: 10
      gains:
        joint2_to_joint1:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        joint3_to_joint2:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        joint4_to_joint3:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        joint5_to_joint4:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        joint6_to_joint5:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        joint6output_to_joint6:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
controller_list:
      - name: arm_position_controller
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - joint2_to_joint1
          - joint3_to_joint2
          - joint4_to_joint3
          - joint5_to_joint4
          - joint6_to_joint5
          - joint6output_to_joint6
