<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="xarm_vacuum_gripper">
<!--
  Author: Jason Peng <jason@ufactory.cc>
-->
  <xacro:macro name="objeto" params="prefix:='' attach_to:='' rpy:='0 0 0' xyz:='0 0 0' 
    objeto_type:='box' 
    objeto_mass:='0.1' 
    objeto_height:='0.1'
    objeto_radius:='0.1'
    objeto_length:='0.1'
    objeto_width:='0.1'
    objeto_mesh_filename:=''
    objeto_mesh_origin_xyz:='0 0 0'
    objeto_mesh_origin_rpy:='0 0 0'
    objeto_mesh_tcp_xyz:='0 0 0'
    objeto_mesh_tcp_rpy:='0 0 0'
    ">
    <xacro:unless value="${attach_to == ''}">
      <joint name="${prefix}other_objecto_fix" type="fixed">
        <parent link="${attach_to}"/>
        <child link="${prefix}other_objeto_link"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <xacro:if value="${objeto_type == 'mesh'}">
      <xacro:property name="_origin_xyz" value="${objeto_mesh_origin_xyz}"/>
      <xacro:property name="_origin_rpy" value="${objeto_mesh_origin_rpy}"/>
      <xacro:property name="_tcp_xyz" value="${objeto_mesh_tcp_xyz}"/>
      <xacro:property name="_tcp_rpy" value="${objeto_mesh_tcp_rpy}"/>
    </xacro:if>
    <xacro:unless value="${objeto_type == 'mesh'}">
      <xacro:property name="_origin_xyz" value="0 0 ${objeto_height / 2 if objeto_type != 'sphere' else objeto_radius}"/>
      <xacro:property name="_origin_rpy" value="0 0 0"/>
      <xacro:property name="_tcp_xyz" value="0 0 ${objeto_height if objeto_type != 'sphere' else objeto_radius * 2}"/>
      <xacro:property name="_tcp_rpy" value="0 0 0"/>
    </xacro:unless>

    <xacro:if value="${objeto_mesh_filename.startswith('file:///') or objeto_mesh_filename.startswith('package://')}">
      <xacro:property name="_mesh_filename" value="${objeto_mesh_filename}"/>
    </xacro:if>
    <xacro:unless value="${objeto_mesh_filename.startswith('file:///') or objeto_mesh_filename.startswith('package://')}">
      <xacro:property name="_mesh_filename" value="file:///$(find xarm_description)/meshes/other/${objeto_mesh_filename}"/>
    </xacro:unless>

    <link
      name="${prefix}other_objeto_link">
      <inertial>
        <origin
          xyz="0.0 0.0 0.055"
          rpy="0 0 0" />
        <mass
          value="${objeto_mass}" />
        <inertia
          ixx="0.00047106"
          ixy="3.9292E-07"
          ixz="2.6537E-06"
          iyy="0.00033072"
          iyz="-1.0975E-05"
          izz="0.00025642" />
      </inertial>
      <visual>
        <origin
          xyz="${_origin_xyz}"
          rpy="${_origin_rpy}" />
        <geometry>
          <xacro:if value="${objeto_type == 'mesh'}">
            <mesh filename="${_mesh_filename}"/>
          </xacro:if>
          <xacro:if value="${objeto_type == 'sphere'}">
            <sphere radius="${objeto_radius}"/>
          </xacro:if>
          <xacro:if value="${objeto_type == 'cylinder'}">
            <cylinder length="${objeto_height}" radius="${objeto_radius}"/>
          </xacro:if>
          <xacro:if value="${objeto_type != 'mesh' and objeto_type != 'sphere' and objeto_type != 'cylinder'}">
            <box size="${objeto_length} ${objeto_width} ${objeto_height}"/>
          </xacro:if>
        </geometry>
        <material name="White">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin
          xyz="${_origin_xyz}"
          rpy="${_origin_rpy}" />
        <geometry>
          <xacro:if value="${objeto_type == 'mesh'}">
            <mesh filename="${_mesh_filename}"/>
          </xacro:if>
          <xacro:if value="${objeto_type == 'sphere'}">
            <sphere radius="${objeto_radius}"/>
          </xacro:if>
          <xacro:if value="${objeto_type == 'cylinder'}">
            <cylinder length="${objeto_height}" radius="${objeto_radius}"/>
          </xacro:if>
          <xacro:if value="${objeto_type != 'mesh' and objeto_type != 'sphere' and objeto_type != 'cylinder'}">
            <box size="${objeto_length} ${objeto_width} ${objeto_height}"/>
          </xacro:if>
        </geometry>
      </collision>
    </link>

    <link name="${prefix}link_objeto" />

    <joint
      name="${prefix}joint_objeto"
      type="fixed">
      <origin
        xyz="${_tcp_xyz}"
        rpy="${_tcp_rpy}" />
      <parent
        link="${prefix}other_objeto_link" />
      <child
        link="${prefix}link_objeto" />
    </joint>

  </xacro:macro>

</robot>
